/**
 * GitHub Pages host adapter
 *
 * GitHub Pages auto-resolves directory indexes (so `<route>/index.html`
 * works without a URI rewrite) and serves static files from a repo or
 * branch. The one quirk: by default GH Pages runs Jekyll over the
 * artifact, which silently strips paths whose components start with `_`
 * — including `_pages/`, `_importmap/`, `_redirects`, and assets in
 * `_app/` style directories used by various build pipelines. Dropping a
 * `.nojekyll` file at the site root opts out of Jekyll processing
 * entirely. Without it, parts of the site silently disappear.
 *
 * postBuild: writes `dist/.nojekyll` (empty file).
 *
 * GitHub Pages does not consume `_redirects` (that's a
 * Cloudflare/Netlify thing) — page-level redirects go through the
 * meta-refresh HTML the prerender already emits for `redirect:` /
 * `rewrite:` directives.
 *
 * initCi: emits a `.github/workflows/deploy-github-pages.yml` that runs
 * `uniweb build --host=github-pages` and uploads the resulting `dist/`
 * via the official actions/deploy-pages flow. The workflow sets
 * `UNIWEB_BASE` from the repo name at build time so site.yml stays
 * clean and the same source can deploy elsewhere without conflict.
 * See gotcha #15 for the base-path flow.
 */

import { writeFile } from 'node:fs/promises'
import { join } from 'node:path'

const adapter = {
  name: 'github-pages',

  async postBuild({ distDir, onProgress = () => {} }) {
    await writeFile(join(distDir, '.nojekyll'), '')
    onProgress('Wrote .nojekyll (opts out of Jekyll on GitHub Pages)')
  },

  async initCi({ site, packageManager = 'pnpm', nodeVersion = '20' }) {
    const sitePath = site.path
    const workflowPath = `.github/workflows/deploy-github-pages.yml`
    const yaml = renderWorkflow({ sitePath, packageManager, nodeVersion })

    return {
      files: [{ path: workflowPath, content: yaml }],
      postInstructions: [
        `Commit and push ${workflowPath} to your repo's default branch.`,
        `On GitHub: Settings → Pages → Source: GitHub Actions.`,
        `The deploy runs automatically on every push to that branch.`,
        ``,
        `Notes:`,
        `  • The workflow sets UNIWEB_BASE=/<repo>/ at build time, so site.yml`,
        `    stays clean and other deploy targets aren't affected.`,
        `  • For a custom domain or a <user>.github.io profile repo (served at`,
        `    root), edit the workflow's UNIWEB_BASE line to '/'.`,
      ],
    }
  },
}

function renderWorkflow({ sitePath, packageManager, nodeVersion }) {
  const isPnpm = packageManager === 'pnpm'
  const setupSteps = isPnpm
    ? `      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - uses: actions/setup-node@v4
        with:
          node-version: '${nodeVersion}'
          cache: pnpm
      - run: pnpm install --frozen-lockfile`
    : `      - uses: actions/setup-node@v4
        with:
          node-version: '${nodeVersion}'
          cache: npm
      - run: npm ci`

  const buildCmd = isPnpm
    ? 'pnpm exec uniweb build --host=github-pages'
    : 'npx uniweb build --host=github-pages'

  return `# Deploy to GitHub Pages
# Generated by \`uniweb add ci --host=github-pages\`. Safe to edit.

name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: \${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4
${setupSteps}
      - run: ${buildCmd}
        env:
          # Sets the site's base path to /<repo>/ at build time only.
          # Override to '/' if deploying to a custom domain or a
          # <user>.github.io profile repo (both serve at root).
          UNIWEB_BASE: /\${{ github.event.repository.name }}/
      - uses: actions/configure-pages@v5
      - uses: actions/upload-pages-artifact@v3
        with:
          path: ${sitePath}/dist
      - id: deployment
        uses: actions/deploy-pages@v4
`
}

export default adapter
