// Localization round-trip plumbing for the site-content projection.
//
// A localized field on a pulled document carries one value per locale:
// `{ en: 'Home', es: 'Inicio' }`. The framework's file surface stores the SOURCE
// locale inline (page.yml::title, a section .md body, …) and the TARGET locales in
// the parallel `locales/` folder, keyed by an 8-char content hash of the source
// text (the same hashing `uniweb i18n extract` uses — `i18n/hash.js`).
//
// Canonical form (Diego, 2026-05-31): the section-scoped translation map travels
// WITH the entity; the global hash manifest (`locales/manifest.json`) is a DERIVABLE
// file-side projection regenerated by `uniweb i18n extract`. So on projection we
// write only `locales/{locale}.json` (hash → target) — the manifest is NOT
// hand-written here; running extract over the projected source files rebuilds it.
//
// This module is the shared read/write layer for that `locales/{locale}.json`
// surface, used by the projector (pull → files) and, later, the producer
// (files → push).

import { readFileSync, writeFileSync, existsSync, mkdirSync, readdirSync, statSync } from 'node:fs'
import { join, dirname } from 'node:path'
import yaml from 'js-yaml'
import { YAML_OPTIONS } from '../utils/yaml-schema.js'
import { proseMirrorToMarkdown, serializeInlineContent } from '@uniweb/content-writer'
import { computeHash } from '../i18n/hash.js'
import { blockElements, elementText, dataBlockNodes } from '../i18n/extract.js'
import { visitDataStrings } from '../i18n/data-strings.js'
import { resolveDocForLocale } from '../i18n/merge.js'
import { computeSourceHash } from '../i18n/freeform-manifest.js'
import { sameMarkdownDocument, canonicalJson } from './same-content.js'

const FREEFORM_MANIFEST = '.manifest.json'

// The directory a site keeps its translations in — `site.yml`'s `i18n.localesDir`, else `locales`,
// the rule the build and `uniweb i18n` read it by — for the push and the pull alike. `subdir` scopes a
// lane: '' → site-content (locales/), 'records' → record translations (locales/records/), matching the
// i18n manifest layout.
// ⛔ It was `locales/` whatever the site said until 2026-09-26: a site keeping its translations in
// `translations/` pushed its source language alone, and a pull wrote into a directory it never read.
export function localesDir(siteRoot, subdir = '') {
  const base = join(siteRoot, localesDirName(siteRoot))
  return subdir ? join(base, subdir) : base
}

// `i18n.localesDir`, read once per version of the file — every translation a pull writes asks for it.
const localesDirCache = new Map() // siteRoot → { mtimeMs, name }
function localesDirName(siteRoot) {
  const file = join(siteRoot, 'site.yml')
  let mtimeMs = null
  try {
    mtimeMs = statSync(file).mtimeMs
  } catch {
    return 'locales'
  }
  const cached = localesDirCache.get(siteRoot)
  if (cached && cached.mtimeMs === mtimeMs) return cached.name
  let name = 'locales'
  try {
    const dir = yaml.load(readFileSync(file, 'utf8'), YAML_OPTIONS)?.i18n?.localesDir
    if (typeof dir === 'string' && dir.trim()) name = dir.trim()
  } catch {
    // unreadable — the default
  }
  localesDirCache.set(siteRoot, { mtimeMs, name })
  return name
}

export function localeFilePath(siteRoot, locale, subdir = '') {
  return join(localesDir(siteRoot, subdir), `${locale}.json`)
}

// True for a `{ <lang>: value }` localized map (vs a bare scalar / array / null).
export function isLocalizedMap(value) {
  return value != null && typeof value === 'object' && !Array.isArray(value)
}

/**
 * Read `locales/{locale}.json` for each target locale into `{ locale: { hash: tgt } }`.
 * The producer's counterpart to writeLocaleTranslations — used to wrap source values
 * back into per-locale form on push. Missing / unreadable files are skipped.
 */
/**
 * Discover the target locales present on disk for a lane — the `{locale}.json`
 * files in `locales/[subdir]/` (excluding the derived `manifest.json` and dotfiles).
 * Lets the producer wrap exactly the locales that have translation files, without
 * re-reading the site's declared language list (a declared-but-empty locale has
 * nothing to wrap anyway).
 */
export function discoverLocales(siteRoot, subdir = '') {
  const dir = localesDir(siteRoot, subdir)
  if (!existsSync(dir)) return []
  try {
    return readdirSync(dir)
      .filter((f) => f.endsWith('.json') && f !== 'manifest.json' && !f.startsWith('.'))
      .map((f) => f.slice(0, -'.json'.length))
  } catch {
    return []
  }
}

// Locales that have a free-form override directory (`locales/freeform/{locale}/`),
// across all lanes. A section or collection record may be localized ONLY by a
// free-form body, with no structural-translation `{locale}.json` to discover it
// from — so the collections producer unions these with discoverLocales.
export function discoverFreeformLocales(siteRoot) {
  const dir = join(localesDir(siteRoot), 'freeform')
  if (!existsSync(dir)) return []
  try {
    return readdirSync(dir, { withFileTypes: true })
      .filter((e) => e.isDirectory())
      .map((e) => e.name)
  } catch {
    return []
  }
}

export function loadLocaleTranslations(siteRoot, locales, subdir = '') {
  const out = {}
  for (const locale of locales || []) {
    const filePath = localeFilePath(siteRoot, locale, subdir)
    if (!existsSync(filePath)) continue
    try {
      const parsed = JSON.parse(readFileSync(filePath, 'utf8'))
      if (parsed && typeof parsed === 'object' && !Array.isArray(parsed)) out[locale] = parsed
    } catch {
      // unreadable / invalid → skip
    }
  }
  return out
}

/**
 * Wrap a section's source-locale content DOC into its localized `content` form: the
 * source locale stays the doc, and EACH TARGET LOCALE BECOMES A SELF-CONTAINED DOC
 * (not a structural map) — resolved from the doc's source structure joined with
 * `locales/{locale}.json` via the merge resolver. A self-contained doc is the
 * portable, renderer-ready form — a source-keyed map is an authoring representation
 * that must be resolved against the source before it can be rendered; the structural
 * map lives only on disk (`locales/{locale}.json`) and is recovered on pull (see
 * unwrapLocalizedContent).
 *
 * ALWAYS returns the per-locale map — `{ [sourceLocale]: doc }` at minimum. A target
 * locale with no translation for THIS doc is omitted (it falls back to the source
 * locale through the delivery locale chain), so the payload stays lean.
 *
 * It used to return the bare doc when nothing had been translated, which made the
 * wire shape depend on *whether a given section happened to have a translation* —
 * so one push could carry a map for a translated section and a bare doc for its
 * untranslated neighbour, on the same page. The field declares `localized: true`,
 * and a bare doc makes that declaration false: `{type, content}` is an object, so
 * it satisfies "must be a map" with `type` and `content` sitting where locale codes
 * belong, and a store cannot validate the one property the field declares. Every
 * reader then has to disambiguate by asking "does this object happen to look like a
 * ProseMirror doc" — a heuristic that has to be implemented identically in three
 * codebases forever, and has already fail-opened in one of them.
 *
 * `localizeScalar` below has always wrapped unconditionally, so the producer was
 * also inconsistent with itself: a section's `title` shipped as `{en: …}` while its
 * `content` shipped bare, in the same payload.
 *
 * Readers stay tolerant of the bare form permanently — it exists in stores, in
 * `.uwx` files on disk, and in every backup taken before this change. This changes
 * what we WRITE, never what we accept (see `isLocalizedContent`, and
 * `unwrapLocalizedContent`, which returns `content[sourceLocale]` so a source-only
 * map round-trips back to a bare doc on the file lane).
 *
 * @param {object} doc - the source-locale ProseMirror content doc
 * @param {string} sourceLocale
 * @param {string[]} [targetLocales]
 * @param {object} [translations] - `{ locale: { hash: tgt } }` from loadLocaleTranslations
 */
export function localizeContentDoc(doc, sourceLocale, targetLocales, translations, context = undefined) {
  // Non-docs (null, an already-localized map) pass through untouched.
  if (!isProseMirrorDoc(doc)) return doc

  const result = { [sourceLocale]: doc }
  if (targetLocales && translations) {
    for (const locale of targetLocales) {
      const table = translations[locale]
      if (!table) continue
      // With the section's context, so a context-specific override resolves as the build resolves it.
      const resolved = resolveDocForLocale(doc, table, context)
      if (resolved) result[locale] = resolved
    }
  }
  return result
}

/**
 * Wrap a SCALAR field value into its localized `{ <lang>: value }` form: the source
 * locale plus any target locales whose `locales/{locale}.json` carries a translation
 * for this exact source text (`hash(value)`). The inverse of the projector's scalar
 * collector. An already-localized object passes through; null/undefined → undefined.
 *
 * @param {*} value
 * @param {string} sourceLocale
 * @param {object} [translations] - `{ locale: { hash: tgt } }` from loadLocaleTranslations
 */
export function localizeScalar(value, sourceLocale, translations) {
  if (value == null) return undefined
  if (typeof value === 'object') return value // already a { lang: value } map
  const out = { [sourceLocale]: value }
  if (translations && typeof value === 'string') {
    const hash = computeHash(value)
    for (const [locale, table] of Object.entries(translations)) {
      const tgt = table?.[hash]
      if (typeof tgt === 'string') out[locale] = tgt
    }
  }
  return out
}

/**
 * Wrap a `multiple: true` + `localized: true` field (e.g. page `keywords` — "array
 * of localized strings") into per-locale form by localizing each element. Container
 * shape is preserved so the round-trip is a fixed point: an array authored as an
 * array stays an array of `{ <lang>: value }` maps; a bare scalar (the degenerate
 * single-value authoring) wraps as one localized scalar. null/undefined → undefined.
 *
 * @param {*} value
 * @param {string} sourceLocale
 * @param {object} [translations] - `{ locale: { hash: tgt } }` from loadLocaleTranslations
 */
export function localizeScalarList(value, sourceLocale, translations) {
  if (value == null) return undefined
  if (!Array.isArray(value)) return localizeScalar(value, sourceLocale, translations)
  return value.map((item) => localizeScalar(item, sourceLocale, translations))
}

// True for a ProseMirror document node (`{ type: 'doc', content: [...] }`).
export function isProseMirrorDoc(value) {
  return value != null && typeof value === 'object' && value.type === 'doc'
}

// A localized `content` field carries one value per locale: the SOURCE locale is a
// ProseMirror doc, a TARGET locale is either a structural `{ src-text: target }`
// map (the default) or a full doc (free-form override). A bare doc (no locale wrap)
// is the source-only / pre-localization shape — left as-is.
export function isLocalizedContent(value) {
  return isLocalizedMap(value) && !isProseMirrorDoc(value)
}

/**
 * Accumulate target-locale translations for localized SCALAR fields across a
 * projection, then flush them to `locales/{locale}.json`. The source-locale value
 * is written inline by the caller (page.yml / site.yml); this captures the rest.
 *
 * `add(localizedValue)` records, for each non-source locale, `hash(source) → target`
 * (source text hashed exactly as `i18n extract` keys it). Non-string or missing
 * values are skipped (only hashable scalars belong in the hash manifest).
 */
export function createTranslationCollector(sourceLocale, { siteRoot = null } = {}) {
  const byLocale = {} // { locale: { hash: target } }
  const freeformPending = [] // [{ locale, content }] — target-locale free-form bodies

  // Record a localized SCALAR field's target locales (hash of the source scalar).
  function add(localizedValue) {
    if (!isLocalizedMap(localizedValue)) return
    const source = localizedValue[sourceLocale]
    if (typeof source !== 'string' || source.length === 0) return
    const hash = computeHash(source)
    for (const [locale, value] of Object.entries(localizedValue)) {
      if (locale === sourceLocale) continue
      if (typeof value !== 'string') continue
      const table = (byLocale[locale] ||= {})
      if (table[hash] instanceof SeenInContexts) table[hash].plain = value
      else table[hash] = value
    }
  }

  // Record a structural translation MAP for one target locale: `{ src-text: target }`
  // keyed by the source text exactly as `i18n extract` keys it (hash of the source).
  // ⭐ With `context` — where the map was read (`translationContext`) — a translation that differs
  // from one section to another is kept per section, and comes back as the author's
  // context-specific overrides (`writeLocaleTranslations`). ⛔ Until 2026-09-26 the last section
  // read won, and a pull wrote that one string over the author's `{ default, overrides }`.
  function addStructuralMap(locale, map, context = null) {
    if (locale === sourceLocale || !map || typeof map !== 'object' || Array.isArray(map)) return
    const table = (byLocale[locale] ||= {})
    for (const [src, target] of Object.entries(map)) {
      if (typeof src !== 'string' || typeof target !== 'string') continue
      const hash = computeHash(src)
      if (!context) {
        if (table[hash] instanceof SeenInContexts) table[hash].plain = target
        else table[hash] = target
        continue
      }
      const seen = table[hash] instanceof SeenInContexts ? table[hash] : new SeenInContexts(table[hash])
      seen.values[`${context.page}:${context.section}`] = target
      table[hash] = seen
    }
  }

  // Note a target-locale FREE-FORM body (a full doc override): `target` is the
  // translated doc, `source` is the source-locale doc (for the staleness hash), and
  // `relpath` is the freeform file path (locale-independent, from buildFreeformPath)
  // — null when the caller can't place it (e.g. layout sections have no freeform
  // home), so it's surfaced rather than dropped.
  function noteFreeform(locale, target, source, relpath) {
    freeformPending.push({ locale, target, source, relpath: relpath || null })
  }

  // ⭐ The FREE-FORM file the site keeps for this translation, if any — the first of `relpaths` (the
  // order the renderer looks them up in, `freeformPathsFor`) that exists for `locale`. A pulled
  // translation goes back into that file, whatever its shape. ⛔ Until 2026-09-25 a free-form body
  // whose paragraphs lined up with its source's was read as a structural translation, and a pull into
  // the author's copy wrote its text over their `locales/{locale}.json` entries for those paragraphs —
  // measured on the `international` template's `about/story`, in Spanish and French.
  function keptFreeform(locale, relpaths) {
    if (!siteRoot) return null
    for (const rel of [].concat(relpaths || [])) {
      if (rel && existsSync(join(localesDir(siteRoot), 'freeform', locale, rel))) return rel
    }
    return null
  }

  return { add, addStructuralMap, noteFreeform, keptFreeform, byLocale, freeformPending }
}

/**
 * Derive a structural `{ source-text: target-inline-markdown }` map from a
 * (source doc, target doc) pair — the inverse of resolveDocForLocale, used on pull
 * to recover the compact `locales/{locale}.json` surface from the DOC the wire now
 * carries. Returns the map when the target is structurally CONGRUENT with the
 * source (same sequence of block elements by type) so it round-trips losslessly;
 * returns null when the target diverges (the caller stores it as a free-form body
 * instead). An element whose inline markdown is identical to the source is
 * untranslated and omitted. The value is the target element's inline content as
 * inline markdown (serializeInlineContent), so emphasis, inline icons, and
 * per-locale link hrefs survive. Keyed by the source element's cleaned text, so
 * `computeHash(key)` matches the extractor's unit hash — closing the round trip.
 */
function deriveStructuralMap(sourceDoc, targetDoc) {
  if (!isProseMirrorDoc(sourceDoc) || !isProseMirrorDoc(targetDoc)) return null
  const src = blockElements(sourceDoc)
  const tgt = blockElements(targetDoc)
  if (src.length !== tgt.length) return null // structurally divergent → free-form
  const map = {}
  try {
    for (let i = 0; i < src.length; i++) {
      if (src[i].type !== tgt[i].type) return null // divergent → free-form
      const key = elementText(src[i])
      if (!key) continue
      const srcMd = serializeInlineContent(src[i].content || [])
      const tgtMd = serializeInlineContent(tgt[i].content || [])
      if (srcMd === tgtMd) continue // unchanged → untranslated → omit
      map[key] = tgtMd
    }
  } catch {
    // a mark we can't serialize → don't risk a lossy map; store as free-form
    return null
  }
  return addDataBlockStrings(map, sourceDoc, targetDoc)
}

// ⭐ A TAGGED DATA BLOCK's translated strings, read pairwise — the strings the build translates
// (`visitDataStrings`, the extractor's judgement), keyed by their source text as the build keys them.
// A target that is not the source with only those strings changed — another shape, another `href` —
// cannot be said per string, and the whole translation is free-form. ⛔ Until 2026-09-26 a data block
// was not read here at all, and its translations were not sent (`merge.js::translateDataBlocks`).
function addDataBlockStrings(map, sourceDoc, targetDoc) {
  const srcBlocks = dataBlockNodes(sourceDoc)
  const tgtBlocks = dataBlockNodes(targetDoc)
  if (srcBlocks.length !== tgtBlocks.length) return null
  for (let i = 0; i < srcBlocks.length; i++) {
    const s = srcBlocks[i].attrs || {}
    const t = tgtBlocks[i].attrs || {}
    if (s.tag !== t.tag) return null
    if (!s.data || typeof s.data !== 'object') {
      if (canonicalJson(s.data) !== canonicalJson(t.data)) return null
      continue
    }
    const strings = (data) => {
      const out = []
      visitDataStrings(JSON.parse(JSON.stringify(data ?? null)), (value) => void out.push(value))
      return out
    }
    const from = strings(s.data)
    const to = strings(t.data)
    if (from.length !== to.length) return null
    const pairs = new Map()
    for (let j = 0; j < from.length; j++) {
      if (from[j] === to[j]) continue
      if (pairs.has(from[j]) && pairs.get(from[j]) !== to[j]) return null // one string, two translations
      pairs.set(from[j], to[j])
    }
    const rebuilt = JSON.parse(JSON.stringify(s.data))
    visitDataStrings(rebuilt, (value) => pairs.get(value) ?? value)
    if (canonicalJson(rebuilt) !== canonicalJson(t.data)) return null
    for (const [from, to] of pairs) map[from.trim()] = to
  }
  return map
}

/**
 * Unwrap a (possibly localized) `content` field to the SOURCE-locale ProseMirror
 * doc for the `.md` body, capturing target locales into `collector`. The wire now
 * carries a self-contained DOC per target locale: a target structurally congruent
 * with the source is recovered as a structural `locales/{locale}.json` map (via
 * deriveStructuralMap); a divergent target is a free-form body override → noted
 * with its freeform path (`freeformRelPath`, from buildFreeformPath). A structural
 * map still on the wire (legacy / transition) passes through unchanged. The
 * reserved `@` (and `$`-prefixed) key is opaque metadata — NEVER a locale. A bare
 * doc (no locale wrap) is returned unchanged.
 */
export function unwrapLocalizedContent(content, sourceLocale, collector, freeformRelPath, freeformCandidates = null, context = null) {
  if (!isLocalizedContent(content)) return content
  const source = content[sourceLocale]
  for (const [locale, value] of Object.entries(content)) {
    if (locale === sourceLocale) continue
    if (locale === '@' || locale.startsWith('$')) continue // reserved metadata, not a locale
    if (isProseMirrorDoc(value)) {
      // A translation the site keeps as a free-form file stays one, even when it lines up.
      const kept = collector?.keptFreeform?.(locale, freeformCandidates || freeformRelPath) || null
      const map = kept ? null : deriveStructuralMap(source, value)
      if (map) collector?.addStructuralMap?.(locale, map, context)
      else collector?.noteFreeform?.(locale, value, source, kept || freeformRelPath)
    } else {
      collector?.addStructuralMap?.(locale, value, context)
    }
  }
  return source
}

// A translation read in several sections: what each section's context says, and what a place with
// no context (a page title) says. Reconciled with the author's entry when the file is written.
class SeenInContexts {
  constructor(plain) {
    this.plain = typeof plain === 'string' ? plain : undefined
    this.values = {} // "<page>:<section>" → translation
  }
}

// ⭐ A translation seen in several places comes back as the author keeps it: one string where every
// place agrees, else `{ default, overrides }` — their default and their overrides kept wherever they
// still hold. The default is what the places without an override of their own say (the most of
// them; the author's default when tied, else the first read). An override for a place this pull did
// not see is kept, and one that now says the default is dropped.
function reconcileTranslation(existing, seen) {
  const own = existing && typeof existing === 'object' && existing.overrides && typeof existing.overrides === 'object' ? existing.overrides : {}
  const authoredDefault = typeof existing === 'string' ? existing : existing && typeof existing === 'object' ? existing.default : undefined
  const contexts = Object.entries(seen.values)
  const candidates = [...(seen.plain !== undefined ? [seen.plain] : []), ...contexts.filter(([k]) => !(k in own)).map(([, v]) => v)]
  let def = authoredDefault
  if (candidates.length) {
    const counts = new Map()
    for (const v of candidates) counts.set(v, (counts.get(v) || 0) + 1)
    const most = Math.max(...counts.values())
    const top = [...counts].filter(([, n]) => n === most).map(([v]) => v)
    def = top.includes(authoredDefault) ? authoredDefault : top[0]
  } else if (def === undefined) {
    def = contexts[0]?.[1]
  }
  const overrides = { ...own }
  for (const [k, v] of contexts) {
    if (v === def) delete overrides[k]
    else overrides[k] = v
  }
  return Object.keys(overrides).length ? { default: def, overrides } : def
}

/**
 * Write captured target-locale FREE-FORM bodies to `locales/freeform/{locale}/<relpath>`
 * (markdown, body-only) and record each one's SOURCE hash in that locale's
 * `.manifest.json` for staleness tracking. Sync + idempotent: a body is rewritten
 * only when its markdown changes, and a manifest `recorded` date is (re)stamped only
 * when the source hash changes — so a no-op re-projection is byte-stable. Entries
 * with no `relpath` (unplaceable, e.g. a layout section) are surfaced as `skipped`.
 *
 * @returns {{ written: string[], skipped: object[] }}
 */
export function writeFreeformTranslations(siteRoot, freeformPending) {
  const report = { written: [], skipped: [] }
  if (!Array.isArray(freeformPending) || freeformPending.length === 0) return report

  const byLocale = new Map() // locale → entries[]
  for (const entry of freeformPending) {
    if (!entry?.relpath) {
      report.skipped.push(entry)
      continue
    }
    if (!byLocale.has(entry.locale)) byLocale.set(entry.locale, [])
    byLocale.get(entry.locale).push(entry)
  }

  for (const [locale, entries] of byLocale) {
    const localeDir = join(localesDir(siteRoot), 'freeform', locale)
    const manifestPath = join(localeDir, FREEFORM_MANIFEST)
    let manifest = {}
    if (existsSync(manifestPath)) {
      try {
        const parsed = JSON.parse(readFileSync(manifestPath, 'utf8'))
        if (parsed && typeof parsed === 'object' && !Array.isArray(parsed)) manifest = parsed
      } catch {
        // unreadable → start fresh
      }
    }

    let manifestChanged = false
    for (const { relpath, target, source } of entries) {
      const filePath = join(localeDir, relpath)
      const md = proseMirrorToMarkdown(target)
      const text = md.endsWith('\n') ? md : md + '\n'
      let current = null
      try {
        current = readFileSync(filePath, 'utf8')
      } catch {
        // absent
      }
      // ⭐ A file whose markdown already says this is left as the author wrote it — the writer's
      // markdown is not theirs (blank lines, line breaks), as for a section body (`writeSectionFile`).
      if (current !== text && !(current !== null && sameMarkdownDocument(current.trim(), target))) {
        mkdirSync(dirname(filePath), { recursive: true })
        writeFileSync(filePath, text)
        report.written.push(filePath)
      }
      // Staleness hash of the SOURCE; re-stamp `recorded` only when it changes.
      const hash = computeSourceHash(source)
      const existing = manifest[relpath]
      if (!existing || existing.hash !== hash) {
        manifest[relpath] = { hash, recorded: new Date().toISOString().slice(0, 10) }
        manifestChanged = true
      }
    }

    if (manifestChanged) {
      mkdirSync(localeDir, { recursive: true })
      writeFileSync(manifestPath, JSON.stringify(manifest, null, 2) + '\n')
    }
  }

  return report
}

/**
 * Merge `{ locale: { hash: target } }` into each `locales/{locale}.json`,
 * preserving existing entries (translations for strings not in this projection are
 * kept — `uniweb i18n audit --clean` removes genuine orphans). Keys are sorted so
 * the output is byte-stable / idempotent. Creates `locales/` if absent.
 *
 * @returns {{ [locale: string]: 'updated' | 'unchanged' }}
 */
export function writeLocaleTranslations(siteRoot, byLocale, subdir = '') {
  const report = {}
  for (let [locale, entries] of Object.entries(byLocale || {})) {
    if (!entries || Object.keys(entries).length === 0) continue
    const filePath = localeFilePath(siteRoot, locale, subdir)

    let existing = {}
    if (existsSync(filePath)) {
      try {
        const parsed = JSON.parse(readFileSync(filePath, 'utf8'))
        if (parsed && typeof parsed === 'object' && !Array.isArray(parsed)) existing = parsed
      } catch {
        // unreadable / invalid → start fresh
      }
    }

    // ⭐ A FILE THE PULL ADDS NOTHING TO IS LEFT AS IT IS, and one it does keeps its order: an entry
    // changes in its place, and new ones follow, sorted. ⛔ Until 2026-09-26 every pull re-sorted the
    // whole file by hash — measured on the `international` template, whose `es.json` runs in page
    // order: a pull that changed no translation rewrote all 77 lines.
    // A translation read in several sections becomes the string or the `{ default, overrides }` the
    // author keeps (`reconcileTranslation`).
    entries = Object.fromEntries(
      Object.entries(entries).map(([key, value]) => [key, value instanceof SeenInContexts ? reconcileTranslation(existing[key], value) : value])
    )
    const fresh = Object.keys(entries).filter((key) => !(key in existing)).sort()
    if (fresh.length === 0 && Object.entries(entries).every(([key, value]) => canonicalJson(existing[key]) === canonicalJson(value))) {
      report[locale] = 'unchanged'
      continue
    }
    const merged = {}
    // An entry the pull did not change keeps its value as written — key order included.
    for (const key of Object.keys(existing)) {
      merged[key] = key in entries && canonicalJson(entries[key]) !== canonicalJson(existing[key]) ? entries[key] : existing[key]
    }
    for (const key of fresh) merged[key] = entries[key]
    const next = JSON.stringify(merged, null, 2) + '\n'

    let current = null
    try {
      current = readFileSync(filePath, 'utf8')
    } catch {
      // absent
    }
    if (current === next) {
      report[locale] = 'unchanged'
      continue
    }
    mkdirSync(dirname(filePath), { recursive: true })
    writeFileSync(filePath, next)
    report[locale] = 'updated'
  }
  return report
}
