// Localization round-trip plumbing for the site-content projection.
//
// A localized field on a pulled document carries one value per locale:
// `{ en: 'Home', es: 'Inicio' }`. The framework's file surface stores the SOURCE
// locale inline (page.yml::title, a section .md body, …) and the TARGET locales in
// the parallel `locales/` folder, keyed by an 8-char content hash of the source
// text (the same hashing `uniweb i18n extract` uses — `i18n/hash.js`).
//
// Canonical form (Diego, 2026-05-31): the section-scoped translation map travels
// WITH the entity; the global hash manifest (`locales/manifest.json`) is a DERIVABLE
// file-side projection regenerated by `uniweb i18n extract`. So on projection we
// write only `locales/{locale}.json` (hash → target) — the manifest is NOT
// hand-written here; running extract over the projected source files rebuilds it.
//
// This module is the shared read/write layer for that `locales/{locale}.json`
// surface, used by the projector (pull → files) and, later, the producer
// (files → push).

import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { computeHash } from '../i18n/hash.js'

// The `locales/` directory for a site (the i18n localesDir default; `paths` can
// override it, but the default is `locales` — keep this the single place to change).
export function localesDir(siteRoot) {
  return join(siteRoot, 'locales')
}

export function localeFilePath(siteRoot, locale) {
  return join(localesDir(siteRoot), `${locale}.json`)
}

// True for a `{ <lang>: value }` localized map (vs a bare scalar / array / null).
export function isLocalizedMap(value) {
  return value != null && typeof value === 'object' && !Array.isArray(value)
}

/**
 * Accumulate target-locale translations for localized SCALAR fields across a
 * projection, then flush them to `locales/{locale}.json`. The source-locale value
 * is written inline by the caller (page.yml / site.yml); this captures the rest.
 *
 * `add(localizedValue)` records, for each non-source locale, `hash(source) → target`
 * (source text hashed exactly as `i18n extract` keys it). Non-string or missing
 * values are skipped (only hashable scalars belong in the hash manifest).
 */
export function createTranslationCollector(sourceLocale) {
  const byLocale = {} // { locale: { hash: target } }

  function add(localizedValue) {
    if (!isLocalizedMap(localizedValue)) return
    const source = localizedValue[sourceLocale]
    if (typeof source !== 'string' || source.length === 0) return
    const hash = computeHash(source)
    for (const [locale, value] of Object.entries(localizedValue)) {
      if (locale === sourceLocale) continue
      if (typeof value !== 'string') continue
      ;(byLocale[locale] ||= {})[hash] = value
    }
  }

  return { add, byLocale }
}

/**
 * Merge `{ locale: { hash: target } }` into each `locales/{locale}.json`,
 * preserving existing entries (translations for strings not in this projection are
 * kept — `uniweb i18n audit --clean` removes genuine orphans). Keys are sorted so
 * the output is byte-stable / idempotent. Creates `locales/` if absent.
 *
 * @returns {{ [locale: string]: 'updated' | 'unchanged' }}
 */
export function writeLocaleTranslations(siteRoot, byLocale) {
  const report = {}
  for (const [locale, entries] of Object.entries(byLocale || {})) {
    if (!entries || Object.keys(entries).length === 0) continue
    const filePath = localeFilePath(siteRoot, locale)

    let existing = {}
    if (existsSync(filePath)) {
      try {
        const parsed = JSON.parse(readFileSync(filePath, 'utf8'))
        if (parsed && typeof parsed === 'object' && !Array.isArray(parsed)) existing = parsed
      } catch {
        // unreadable / invalid → start fresh
      }
    }

    const merged = { ...existing, ...entries }
    const sorted = {}
    for (const key of Object.keys(merged).sort()) sorted[key] = merged[key]
    const next = JSON.stringify(sorted, null, 2) + '\n'

    let current = null
    try {
      current = readFileSync(filePath, 'utf8')
    } catch {
      // absent
    }
    if (current === next) {
      report[locale] = 'unchanged'
      continue
    }
    mkdirSync(dirname(filePath), { recursive: true })
    writeFileSync(filePath, next)
    report[locale] = 'updated'
  }
  return report
}
