// Localization round-trip plumbing for the site-content projection.
//
// A localized field on a pulled document carries one value per locale:
// `{ en: 'Home', es: 'Inicio' }`. The framework's file surface stores the SOURCE
// locale inline (page.yml::title, a section .md body, …) and the TARGET locales in
// the parallel `locales/` folder, keyed by an 8-char content hash of the source
// text (the same hashing `uniweb i18n extract` uses — `i18n/hash.js`).
//
// Canonical form (Diego, 2026-05-31): the section-scoped translation map travels
// WITH the entity; the global hash manifest (`locales/manifest.json`) is a DERIVABLE
// file-side projection regenerated by `uniweb i18n extract`. So on projection we
// write only `locales/{locale}.json` (hash → target) — the manifest is NOT
// hand-written here; running extract over the projected source files rebuilds it.
//
// This module is the shared read/write layer for that `locales/{locale}.json`
// surface, used by the projector (pull → files) and, later, the producer
// (files → push).

import { readFileSync, writeFileSync, existsSync, mkdirSync, readdirSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { proseMirrorToMarkdown } from '@uniweb/content-writer'
import { computeHash, stripInlineTags } from '../i18n/hash.js'
import { extractUnitsFromDoc } from '../i18n/extract.js'
import { computeSourceHash } from '../i18n/freeform-manifest.js'

const FREEFORM_MANIFEST = '.manifest.json'

// The `locales/` directory for a site (the i18n localesDir default; `paths` can
// override it, but the default is `locales` — keep this the single place to change).
// `subdir` scopes a lane: '' → site-content (locales/), 'collections' → collection
// records (locales/collections/), matching the i18n manifest layout.
export function localesDir(siteRoot, subdir = '') {
  return subdir ? join(siteRoot, 'locales', subdir) : join(siteRoot, 'locales')
}

export function localeFilePath(siteRoot, locale, subdir = '') {
  return join(localesDir(siteRoot, subdir), `${locale}.json`)
}

// True for a `{ <lang>: value }` localized map (vs a bare scalar / array / null).
export function isLocalizedMap(value) {
  return value != null && typeof value === 'object' && !Array.isArray(value)
}

/**
 * Read `locales/{locale}.json` for each target locale into `{ locale: { hash: tgt } }`.
 * The producer's counterpart to writeLocaleTranslations — used to wrap source values
 * back into per-locale form on push. Missing / unreadable files are skipped.
 */
/**
 * Discover the target locales present on disk for a lane — the `{locale}.json`
 * files in `locales/[subdir]/` (excluding the derived `manifest.json` and dotfiles).
 * Lets the producer wrap exactly the locales that have translation files, without
 * re-reading the site's declared language list (a declared-but-empty locale has
 * nothing to wrap anyway).
 */
export function discoverLocales(siteRoot, subdir = '') {
  const dir = localesDir(siteRoot, subdir)
  if (!existsSync(dir)) return []
  try {
    return readdirSync(dir)
      .filter((f) => f.endsWith('.json') && f !== 'manifest.json' && !f.startsWith('.'))
      .map((f) => f.slice(0, -'.json'.length))
  } catch {
    return []
  }
}

export function loadLocaleTranslations(siteRoot, locales, subdir = '') {
  const out = {}
  for (const locale of locales || []) {
    const filePath = localeFilePath(siteRoot, locale, subdir)
    if (!existsSync(filePath)) continue
    try {
      const parsed = JSON.parse(readFileSync(filePath, 'utf8'))
      if (parsed && typeof parsed === 'object' && !Array.isArray(parsed)) out[locale] = parsed
    } catch {
      // unreadable / invalid → skip
    }
  }
  return out
}

/**
 * Wrap a section's source-locale content DOC into its localized `content` form: the
 * source locale stays the doc; each target locale becomes a structural
 * `{ source-text: target }` map built from the doc's translatable units joined with
 * `locales/{locale}.json`. The map is keyed by the cleaned (inline-tag-stripped)
 * source text, so the projector's `computeHash(key)` matches the unit hash —
 * closing the round trip. Reuses the i18n extractor (extractUnitsFromDoc).
 *
 * Returns the bare doc unchanged when there are no target locales / no translations
 * for any of them (single-locale and pre-localization sites are untouched).
 *
 * @param {object} doc - the source-locale ProseMirror content doc
 * @param {string} sourceLocale
 * @param {string[]} targetLocales
 * @param {object} translations - `{ locale: { hash: tgt } }` from loadLocaleTranslations
 */
export function localizeContentDoc(doc, sourceLocale, targetLocales, translations) {
  if (!isProseMirrorDoc(doc) || !targetLocales || targetLocales.length === 0 || !translations) {
    return doc
  }
  const units = extractUnitsFromDoc(doc)
  const result = { [sourceLocale]: doc }
  for (const locale of targetLocales) {
    const table = translations[locale]
    if (!table) continue
    const map = {}
    for (const [hash, unit] of Object.entries(units)) {
      const tgt = table[hash]
      if (typeof tgt === 'string') map[stripInlineTags(unit.source)] = tgt
    }
    if (Object.keys(map).length > 0) result[locale] = map
  }
  // Only wrap when at least one target carried a translation — else stay a bare doc.
  return Object.keys(result).length > 1 ? result : doc
}

/**
 * Wrap a SCALAR field value into its localized `{ <lang>: value }` form: the source
 * locale plus any target locales whose `locales/{locale}.json` carries a translation
 * for this exact source text (`hash(value)`). The inverse of the projector's scalar
 * collector. An already-localized object passes through; null/undefined → undefined.
 *
 * @param {*} value
 * @param {string} sourceLocale
 * @param {object} [translations] - `{ locale: { hash: tgt } }` from loadLocaleTranslations
 */
export function localizeScalar(value, sourceLocale, translations) {
  if (value == null) return undefined
  if (typeof value === 'object') return value // already a { lang: value } map
  const out = { [sourceLocale]: value }
  if (translations && typeof value === 'string') {
    const hash = computeHash(value)
    for (const [locale, table] of Object.entries(translations)) {
      const tgt = table?.[hash]
      if (typeof tgt === 'string') out[locale] = tgt
    }
  }
  return out
}

/**
 * Wrap a `multiple: true` + `localized: true` field (e.g. page `keywords` — "array
 * of localized strings") into per-locale form by localizing each element. Container
 * shape is preserved so the round-trip is a fixed point: an array authored as an
 * array stays an array of `{ <lang>: value }` maps; a bare scalar (the degenerate
 * single-value authoring) wraps as one localized scalar. null/undefined → undefined.
 *
 * @param {*} value
 * @param {string} sourceLocale
 * @param {object} [translations] - `{ locale: { hash: tgt } }` from loadLocaleTranslations
 */
export function localizeScalarList(value, sourceLocale, translations) {
  if (value == null) return undefined
  if (!Array.isArray(value)) return localizeScalar(value, sourceLocale, translations)
  return value.map((item) => localizeScalar(item, sourceLocale, translations))
}

// True for a ProseMirror document node (`{ type: 'doc', content: [...] }`).
export function isProseMirrorDoc(value) {
  return value != null && typeof value === 'object' && value.type === 'doc'
}

// A localized `content` field carries one value per locale: the SOURCE locale is a
// ProseMirror doc, a TARGET locale is either a structural `{ src-text: target }`
// map (the default) or a full doc (free-form override). A bare doc (no locale wrap)
// is the source-only / pre-localization shape — left as-is.
export function isLocalizedContent(value) {
  return isLocalizedMap(value) && !isProseMirrorDoc(value)
}

/**
 * Accumulate target-locale translations for localized SCALAR fields across a
 * projection, then flush them to `locales/{locale}.json`. The source-locale value
 * is written inline by the caller (page.yml / site.yml); this captures the rest.
 *
 * `add(localizedValue)` records, for each non-source locale, `hash(source) → target`
 * (source text hashed exactly as `i18n extract` keys it). Non-string or missing
 * values are skipped (only hashable scalars belong in the hash manifest).
 */
export function createTranslationCollector(sourceLocale) {
  const byLocale = {} // { locale: { hash: target } }
  const freeformPending = [] // [{ locale, content }] — target-locale free-form bodies

  // Record a localized SCALAR field's target locales (hash of the source scalar).
  function add(localizedValue) {
    if (!isLocalizedMap(localizedValue)) return
    const source = localizedValue[sourceLocale]
    if (typeof source !== 'string' || source.length === 0) return
    const hash = computeHash(source)
    for (const [locale, value] of Object.entries(localizedValue)) {
      if (locale === sourceLocale) continue
      if (typeof value !== 'string') continue
      ;(byLocale[locale] ||= {})[hash] = value
    }
  }

  // Record a structural translation MAP for one target locale: `{ src-text: target }`
  // keyed by the source text exactly as `i18n extract` keys it (hash of the source).
  function addStructuralMap(locale, map) {
    if (locale === sourceLocale || !map || typeof map !== 'object' || Array.isArray(map)) return
    for (const [src, target] of Object.entries(map)) {
      if (typeof src !== 'string' || typeof target !== 'string') continue
      ;(byLocale[locale] ||= {})[computeHash(src)] = target
    }
  }

  // Note a target-locale FREE-FORM body (a full doc override): `target` is the
  // translated doc, `source` is the source-locale doc (for the staleness hash), and
  // `relpath` is the freeform file path (locale-independent, from buildFreeformPath)
  // — null when the caller can't place it (e.g. layout sections have no freeform
  // home), so it's surfaced rather than dropped.
  function noteFreeform(locale, target, source, relpath) {
    freeformPending.push({ locale, target, source, relpath: relpath || null })
  }

  return { add, addStructuralMap, noteFreeform, byLocale, freeformPending }
}

/**
 * Unwrap a (possibly localized) `content` field to the SOURCE-locale ProseMirror
 * doc for the `.md` body, capturing target locales into `collector`: a structural
 * `{ src: target }` map → hash entries; a free-form doc override → noted with its
 * freeform path (`freeformRelPath`, from buildFreeformPath) so it can be written to
 * `locales/freeform/{locale}/…`. A bare doc (no locale wrap) is returned unchanged.
 */
export function unwrapLocalizedContent(content, sourceLocale, collector, freeformRelPath) {
  if (!isLocalizedContent(content)) return content
  const source = content[sourceLocale]
  for (const [locale, value] of Object.entries(content)) {
    if (locale === sourceLocale) continue
    if (isProseMirrorDoc(value)) collector?.noteFreeform?.(locale, value, source, freeformRelPath)
    else collector?.addStructuralMap?.(locale, value)
  }
  return source
}

/**
 * Write captured target-locale FREE-FORM bodies to `locales/freeform/{locale}/<relpath>`
 * (markdown, body-only) and record each one's SOURCE hash in that locale's
 * `.manifest.json` for staleness tracking. Sync + idempotent: a body is rewritten
 * only when its markdown changes, and a manifest `recorded` date is (re)stamped only
 * when the source hash changes — so a no-op re-projection is byte-stable. Entries
 * with no `relpath` (unplaceable, e.g. a layout section) are surfaced as `skipped`.
 *
 * @returns {{ written: string[], skipped: object[] }}
 */
export function writeFreeformTranslations(siteRoot, freeformPending) {
  const report = { written: [], skipped: [] }
  if (!Array.isArray(freeformPending) || freeformPending.length === 0) return report

  const byLocale = new Map() // locale → entries[]
  for (const entry of freeformPending) {
    if (!entry?.relpath) {
      report.skipped.push(entry)
      continue
    }
    if (!byLocale.has(entry.locale)) byLocale.set(entry.locale, [])
    byLocale.get(entry.locale).push(entry)
  }

  for (const [locale, entries] of byLocale) {
    const localeDir = join(localesDir(siteRoot), 'freeform', locale)
    const manifestPath = join(localeDir, FREEFORM_MANIFEST)
    let manifest = {}
    if (existsSync(manifestPath)) {
      try {
        const parsed = JSON.parse(readFileSync(manifestPath, 'utf8'))
        if (parsed && typeof parsed === 'object' && !Array.isArray(parsed)) manifest = parsed
      } catch {
        // unreadable → start fresh
      }
    }

    let manifestChanged = false
    for (const { relpath, target, source } of entries) {
      const filePath = join(localeDir, relpath)
      const md = proseMirrorToMarkdown(target)
      const text = md.endsWith('\n') ? md : md + '\n'
      let current = null
      try {
        current = readFileSync(filePath, 'utf8')
      } catch {
        // absent
      }
      if (current !== text) {
        mkdirSync(dirname(filePath), { recursive: true })
        writeFileSync(filePath, text)
        report.written.push(filePath)
      }
      // Staleness hash of the SOURCE; re-stamp `recorded` only when it changes.
      const hash = computeSourceHash(source)
      const existing = manifest[relpath]
      if (!existing || existing.hash !== hash) {
        manifest[relpath] = { hash, recorded: new Date().toISOString().slice(0, 10) }
        manifestChanged = true
      }
    }

    if (manifestChanged) {
      mkdirSync(localeDir, { recursive: true })
      writeFileSync(manifestPath, JSON.stringify(manifest, null, 2) + '\n')
    }
  }

  return report
}

/**
 * Merge `{ locale: { hash: target } }` into each `locales/{locale}.json`,
 * preserving existing entries (translations for strings not in this projection are
 * kept — `uniweb i18n audit --clean` removes genuine orphans). Keys are sorted so
 * the output is byte-stable / idempotent. Creates `locales/` if absent.
 *
 * @returns {{ [locale: string]: 'updated' | 'unchanged' }}
 */
export function writeLocaleTranslations(siteRoot, byLocale, subdir = '') {
  const report = {}
  for (const [locale, entries] of Object.entries(byLocale || {})) {
    if (!entries || Object.keys(entries).length === 0) continue
    const filePath = localeFilePath(siteRoot, locale, subdir)

    let existing = {}
    if (existsSync(filePath)) {
      try {
        const parsed = JSON.parse(readFileSync(filePath, 'utf8'))
        if (parsed && typeof parsed === 'object' && !Array.isArray(parsed)) existing = parsed
      } catch {
        // unreadable / invalid → start fresh
      }
    }

    const merged = { ...existing, ...entries }
    const sorted = {}
    for (const key of Object.keys(merged).sort()) sorted[key] = merged[key]
    const next = JSON.stringify(sorted, null, 2) + '\n'

    let current = null
    try {
      current = readFileSync(filePath, 'utf8')
    } catch {
      // absent
    }
    if (current === next) {
      report[locale] = 'unchanged'
      continue
    }
    mkdirSync(dirname(filePath), { recursive: true })
    writeFileSync(filePath, next)
    report[locale] = 'updated'
  }
  return report
}
